import { InventoryPart } from "@/components/dummyData/columns";

export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  company?: string;
}

export const customers: Customer[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    company: "ABC Corp",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "098-765-4321",
    company: "XYZ Inc",
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "bob@example.com",
    phone: "555-555-5555",
    company: "123 LLC",
  },
  {
    id: "4",
    name: "Sarah Williams",
    email: "sarah@example.com",
    phone: "222-333-4444",
    company: "Tech Solutions",
  },
  {
    id: "5",
    name: "Michael Brown",
    email: "michael@example.com",
    phone: "777-888-9999",
    company: "Digital Dynamics",
  },
  {
    id: "6",
    name: "Emily Davis",
    email: "emily@example.com",
    phone: "444-555-6666",
    company: "Creative Co",
  },
  {
    id: "7",
    name: "David Wilson",
    email: "david@example.com",
    phone: "111-222-3333",
    company: "Wilson Enterprises",
  },
  {
    id: "8",
    name: "Lisa Anderson",
    email: "lisa@example.com",
    phone: "666-777-8888",
    company: "Anderson & Associates",
  },
  {
    id: "9",
    name: "James Taylor",
    email: "james@example.com",
    phone: "999-000-1111",
    company: "Taylor Industries",
  },
  {
    id: "10",
    name: "Jennifer Martinez",
    email: "jennifer@example.com",
    phone: "333-444-5555",
    company: "Martinez Group",
  },
  {
    id: "11",
    name: "Robert Garcia",
    email: "robert@example.com",
    phone: "888-999-0000",
    company: "Garcia Solutions",
  },
  {
    id: "12",
    name: "Michelle Lee",
    email: "michelle@example.com",
    phone: "777-666-5555",
    company: "Lee Consulting",
  },
  {
    id: "13",
    name: "William Clark",
    email: "william@example.com",
    phone: "444-333-2222",
    company: "Clark Technologies",
  },
];

export const inventory: InventoryPart[] = [
  {
    stockCode: "DHT-B-10-V",
    description: "HANWOOD DHT Lower Sash Meet Rail Bronze Anodized",
    qtyOnHand: 120.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 120.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-B-11-V",
    description: "HANWOOD DHT Lower Sash Bottom Rail Bronze Anodized",
    qtyOnHand: 156.0,
    qtyOnSalesOrder: 8.0,
    qtyOnPurchaseOrder: 120.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-B-12-V",
    description: "HANWOOD DHT Sill Bronze",
    qtyOnHand: 122.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 120.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-B-13-V",
    description: "HANWOOD DHT Upper Sash Side Rail Bronze Anodized",
    qtyOnHand: 270.0,
    qtyOnSalesOrder: 4.0,
    qtyOnPurchaseOrder: 120.0,
    stockLevel: "High",
  },
  {
    stockCode: "DHT-B-14-V",
    description: "Mullion Bronze Anodized 20ft.",
    qtyOnHand: 196.0,
    qtyOnSalesOrder: 9.0,
    qtyOnPurchaseOrder: 90.0,
    stockLevel: "High",
  },
  {
    stockCode: "DHT-B-20-V",
    description: "Picture Window Frame Bronze Anodized",
    qtyOnHand: 95.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 0.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-B-21",
    description: "CDW-21 Combo Mullion Dark Bron",
    qtyOnHand: 28.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 0.0,
    stockLevel: "Critical",
  },
  {
    stockCode: "DHT-B-4-V",
    description: "DHT900 Bronze Header",
    qtyOnHand: 125.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 120.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-B-5-V",
    description: "HANWOOD DHT Upper Sash Top Rail Bronze Anodized",
    qtyOnHand: 134.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 120.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-B-7-V",
    description: "HANWOOD DHT Lower Sash Side Rail Bronze Anodized",
    qtyOnHand: 105.0,
    qtyOnSalesOrder: 12.0,
    qtyOnPurchaseOrder: 150.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-B-8-V",
    description: "HANWOOD DHT Jamb Bronze Anodized",
    qtyOnHand: 524.0,
    qtyOnSalesOrder: 1.0,
    qtyOnPurchaseOrder: 278.0,
    stockLevel: "High",
  },
  {
    stockCode: "DHT-B-9-V",
    description: "HANWOOD DHT Upper Sash Meet Rail Bronze Anodized",
    qtyOnHand: 147.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 120.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-C-10-V",
    description: "HANWOOD DHT Lower Sash Meet Rail Clear Anodized",
    qtyOnHand: 87.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 60.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-C-11-V",
    description: "HANWOOD DHT Lower Sash Bottom Rail Clear Anodized",
    qtyOnHand: 118.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 60.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-C-12-V",
    description: "HANWOOD DHT Sill Clear Anodized",
    qtyOnHand: 113.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 60.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-C-13-V",
    description: "HANWOOD DHT Upper Sash Side Rail Clear Anodized",
    qtyOnHand: 13.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 110.0,
    stockLevel: "Critical",
  },
  {
    stockCode: "DHT-C-14-V",
    description: "HANWOOD DHT T-Mullion Mill Finish",
    qtyOnHand: 143.0,
    qtyOnSalesOrder: 2.0,
    qtyOnPurchaseOrder: 60.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-C-20-V",
    description: "Picture Window Frame Clear Anodized",
    qtyOnHand: 102.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 0.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-C-21",
    description: "CDW-21 Combo Mullion Clear",
    qtyOnHand: 12.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 0.0,
    stockLevel: "Critical",
  },
  {
    stockCode: "DHT-C-4-V",
    description: "HANWOOD DHT Header Clear Anodized",
    qtyOnHand: 83.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 60.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-C-5-V",
    description: "HANWOOD DHT Upper Sash Top Rail Clear Anodized",
    qtyOnHand: 101.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 60.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-C-7-V",
    description: "HANWOOD DHT Lower Sash Side Rail Clear Anodized",
    qtyOnHand: 29.0,
    qtyOnSalesOrder: 7.0,
    qtyOnPurchaseOrder: 110.0,
    stockLevel: "Critical",
  },
  {
    stockCode: "DHT-C-8-V",
    description: "HANWOOD DHT Jamb Clear Anodized",
    qtyOnHand: 179.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 300.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-C-9-V",
    description: "HANWOOD DHT Upper Sash Meet Rail Clear Anodized",
    qtyOnHand: 89.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 60.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-10-V",
    description: "HANWOOD DHT Lower Sash Meet Rail White",
    qtyOnHand: 32.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 200.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-11-V",
    description: "HANWOOD DHT Lower Sash Bottom Rail White",
    qtyOnHand: 41.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 150.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-12-V",
    description: "HANWOOD DHT Sill White",
    qtyOnHand: 66.0,
    qtyOnSalesOrder: 11.0,
    qtyOnPurchaseOrder: 150.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-13-V",
    description: "HANWOOD DHT Upper Sash Side Rail White",
    qtyOnHand: 24.0,
    qtyOnSalesOrder: 2.0,
    qtyOnPurchaseOrder: 200.0,
    stockLevel: "Critical",
  },
  {
    stockCode: "DHT-W-14-V",
    description: "DHT T-Mullion White",
    qtyOnHand: 60.0,
    qtyOnSalesOrder: 12.0,
    qtyOnPurchaseOrder: 150.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-20-V",
    description: "Picture Frame White",
    qtyOnHand: 111.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 0.0,
    stockLevel: "Medium",
  },
  {
    stockCode: "DHT-W-21-B",
    description: "DHT900 White Combo Mullion",
    qtyOnHand: 62.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 0.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-4-V",
    description: "HANWOOD DHT Header White",
    qtyOnHand: 67.0,
    qtyOnSalesOrder: 11.0,
    qtyOnPurchaseOrder: 150.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-5-V",
    description: "DHT900 W Upper Sash Top Rail",
    qtyOnHand: 34.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 150.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-7-V",
    description: "HANWODD DHT Lower Sash Side Rail White",
    qtyOnHand: 4.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 205.0,
    stockLevel: "Critical",
  },
  {
    stockCode: "DHT-W-8-V",
    description: "HANWOOD DHT Jamb White",
    qtyOnHand: 266.0,
    qtyOnSalesOrder: 44.0,
    qtyOnPurchaseOrder: 350.0,
    stockLevel: "Low",
  },
  {
    stockCode: "DHT-W-9-V",
    description: "HANWOOD DHT Upper Sash Meet Rail White",
    qtyOnHand: 19.0,
    qtyOnSalesOrder: 0.0,
    qtyOnPurchaseOrder: 200.0,
    stockLevel: "Critical",
  },
];
